INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (1, 'Jesús', 'Zúñiga Trejo', 'Débito', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (2, 'Ana', 'Alejandre Arroyo', 'Crédito', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (3, 'Ada', 'Lovelace', 'Bitcoins', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (4, 'Ana', 'De Armas', 'Paypal', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (5, 'Alicia', 'Vikander', 'Débito', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (6, 'Amber', 'Heard', 'Crédito', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (7, 'Nathalie', 'Emmanuel', 'Dominican Peso', NULL, '2022-03-04 10:46:31');
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (8, 'Julia', 'Styles', 'Afghani', NULL, '2022-03-04 10:44:01');
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (9, 'Natalie', 'Dormer', 'European Unit of Account 9(E.U.A.-9)', NULL, '2022-03-04 10:50:25');
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (10, 'Rosa María', 'Villalobos', 'Djibouti Franc', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (11, 'Carice', 'Van Houten', 'Pound Sterling', NULL, '2022-03-04 10:47:32');
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (12, 'Monica', 'Galindo', 'Lithuanian Litas', NULL, '2022-03-04 10:43:06');
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (13, 'Estela', 'Rentería', 'US Dollar', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (14, 'Liliana', 'Ramírez', 'Rand', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (15, 'Martha', 'Aranda', 'Saudi Riyal', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (16, 'Edith', 'de la Torre', 'Sudanese Pound', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (17, 'Leonor', 'Watling', 'Débito', '2022-03-04 10:23:25', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (18, 'Paz', 'Vega', 'Crédito', '2022-03-04 10:24:18', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (19, 'Maribel', 'Verdú', 'Efectivo', '2022-03-04 10:25:53', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (20, 'Elena', 'Anaya', 'Bitcoins', '2022-03-04 10:26:51', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (21, 'Natasha', 'Yarovenko', 'Paypal', '2022-03-04 10:27:46', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (22, 'Angie', 'Cepeda', 'Pesos Colombianos', '2022-03-04 10:28:47', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (23, 'Eréndira', 'Ibarra', 'Doláres Australianos', '2022-03-04 10:36:24', '2022-03-04 11:15:31');
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (24, 'Adriana', 'Paz', 'Pesos Mexicanos', '2022-03-04 11:09:56', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (25, 'Sasha', 'González', 'Pesos Mexicanos', '2022-03-04 11:13:23', NULL);
INSERT INTO alumnos (id, apellido, nombre) VALUES (1, 'Castillo', 'Reyna');
INSERT INTO alumnos (id, apellido, nombre) VALUES (2, 'Guillén', 'Eduardo');
INSERT INTO alumnos (id, apellido, nombre) VALUES (3, 'Ojeda', 'Rosario');
INSERT INTO alumnos (id, apellido, nombre) VALUES (4, 'Varela', 'Daniel');
INSERT INTO alumnos (id, apellido, nombre) VALUES (5, 'Pérez', 'Agustina');
INSERT INTO alumnos (id, apellido, nombre) VALUES (6, 'Medrano', 'Pablo');
INSERT INTO alumnos (id, apellido, nombre) VALUES (7, 'Espinoza', 'Leticia');
INSERT INTO alumnos (id, apellido, nombre) VALUES (8, 'Sotelo', 'Martha');
INSERT INTO alumnos (id, apellido, nombre) VALUES (9, 'Murillo', 'Héctor');
INSERT INTO alumnos (id, apellido, nombre) VALUES (10, 'Fuentes', 'Francisco');
INSERT INTO alumnos (id, apellido, nombre) VALUES (11, 'Cárdenas', 'César');
INSERT INTO alumnos (id, apellido, nombre) VALUES (12, 'Miranda', 'Lorena');
INSERT INTO alumnos (id, apellido, nombre) VALUES (13, 'Ibarra', 'Jesús');
INSERT INTO alumnos (id, apellido, nombre) VALUES (14, 'Marín', 'Consuelo');
INSERT INTO alumnos (id, apellido, nombre) VALUES (15, 'Torres', 'Cecilia');
INSERT INTO alumnos (id, apellido, nombre) VALUES (16, 'Villarreal', 'David');
INSERT INTO alumnos (id, apellido, nombre) VALUES (17, 'Romo', 'Ernesto');
INSERT INTO alumnos (id, apellido, nombre) VALUES (18, 'Carrera', 'Ignacio');
INSERT INTO alumnos (id, apellido, nombre) VALUES (19, 'de la Cruz', 'Cecilia');
INSERT INTO alumnos (id, apellido, nombre) VALUES (20, 'Quezada', 'Andrea');
INSERT INTO cursos (id, profesor, titulo) VALUES (1, 'Srita. Sergio Pérez Cortez', 'Beyond the Mexique Bay');
INSERT INTO cursos (id, profesor, titulo) VALUES (2, 'Dr. Pablo Olvera Cárdenas', 'Tender Is the Night');
INSERT INTO cursos (id, profesor, titulo) VALUES (3, 'Concepción Granados Félix', 'A Farewell to Arms');
INSERT INTO cursos (id, profesor, titulo) VALUES (4, 'Víctor Zárate Domínguez', 'Endless Night');
INSERT INTO cursos (id, profesor, titulo) VALUES (5, 'Ing. David Rodríguez de Jesús', 'His Dark Materials');
INSERT INTO cursos (id, profesor, titulo) VALUES (6, 'Eva de León Esquivel', 'A Glass of Blessings');
INSERT INTO cursos (id, profesor, titulo) VALUES (7, 'Sra. Micaela Santos Méndez', 'The Proper Study');
INSERT INTO cursos (id, profesor, titulo) VALUES (8, 'Ing. Esther Toledo Salinas', 'Blood\'s a Rover');
INSERT INTO cursos (id, profesor, titulo) VALUES (9, 'Sara Beltrán Escamilla', 'The Last Temptation');
INSERT INTO cursos (id, profesor, titulo) VALUES (10, 'Marco Antonio Mejía Castañeda', 'The Green Bay Tree');
INSERT INTO cursos (id, profesor, titulo) VALUES (11, 'Miriam Santillán Alfaro', 'Brandy of the Damned');
INSERT INTO cursos (id, profesor, titulo) VALUES (12, 'Ing. Alfredo Vega Escobedo', 'The Man Within');
INSERT INTO cursos (id, profesor, titulo) VALUES (13, 'Sr. Sonia Escobedo Fuentes', 'Gone with the Wind');
INSERT INTO cursos (id, profesor, titulo) VALUES (14, 'Sra. Ramiro Pérez Carrera', 'The Cricket on the Hearth');
INSERT INTO cursos (id, profesor, titulo) VALUES (15, 'Srita. Samuel Márquez Pacheco', 'Surprised by Joy');
INSERT INTO cursos (id, profesor, titulo) VALUES (16, 'Rafael Jímenez del Ángel', 'Antic Hay');
INSERT INTO cursos (id, profesor, titulo) VALUES (17, 'Teresa Vidal Leal', 'Wildfire at Midnight');
INSERT INTO cursos (id, profesor, titulo) VALUES (18, 'Vicente Trejo Vera', 'Now Sleeps the Crimson Petal');
INSERT INTO cursos (id, profesor, titulo) VALUES (19, 'Dr. Antonio Godínez Valadez', 'Waiting for the Barbarians');
INSERT INTO cursos (id, profesor, titulo) VALUES (20, 'Eduardo Rendón de los Santos', 'The Proper Study');
INSERT INTO direcciones (id, calle, numero) VALUES (1, 'Parque Patricia', 450);
INSERT INTO direcciones (id, calle, numero) VALUES (2, 'Parque Huimilpan', 600);
INSERT INTO direcciones (id, calle, numero) VALUES (3, 'Entrada Altar', 377);
INSERT INTO direcciones (id, calle, numero) VALUES (4, 'Arroyo Rodrigo', 174);
INSERT INTO direcciones (id, calle, numero) VALUES (5, 'Bajada Julia Covarrubias', 655);
INSERT INTO direcciones (id, calle, numero) VALUES (6, 'Privada Citlaltepetl', 643);
INSERT INTO direcciones (id, calle, numero) VALUES (7, 'Privada Teapa', 751);
INSERT INTO direcciones (id, calle, numero) VALUES (8, 'Manzana Aguascalientes', 35);
INSERT INTO direcciones (id, calle, numero) VALUES (9, 'Vía Doctor Mora', 65);
INSERT INTO direcciones (id, calle, numero) VALUES (10, 'Lago San Luis Potosí', 232);
INSERT INTO direcciones (id, calle, numero) VALUES (11, 'Conjunto Liliana Olvera', 282);
INSERT INTO direcciones (id, calle, numero) VALUES (12, 'Plaza Sonora', 267);
INSERT INTO direcciones (id, calle, numero) VALUES (13, 'Salida Rafael Correa', 200);
INSERT INTO direcciones (id, calle, numero) VALUES (14, 'Pasaje Ramiro Maldonado', 163);
INSERT INTO direcciones (id, calle, numero) VALUES (15, 'Plaza Sandra', 813);
INSERT INTO direcciones (id, calle, numero) VALUES (16, 'Jardines Morelos', 74);
INSERT INTO direcciones (id, calle, numero) VALUES (17, 'Barranco Antonio', 215);
INSERT INTO direcciones (id, calle, numero) VALUES (18, 'Vía Beatriz', 11);
INSERT INTO direcciones (id, calle, numero) VALUES (19, 'Quinta Beatriz Zepeda', 411);
INSERT INTO direcciones (id, calle, numero) VALUES (20, 'Escalinata Francisco', 894);
INSERT INTO direcciones (id, calle, numero) VALUES (21, 'Mirella Prairie', 803);
INSERT INTO direcciones (id, calle, numero) VALUES (22, 'Maynard Drive', 681);
INSERT INTO tbl_clientes_direcciones (id_cliente, id_direccion) VALUES (21, 21);
INSERT INTO tbl_clientes_direcciones (id_cliente, id_direccion) VALUES (21, 22);
INSERT INTO clientes_detalles (id, prime, puntos_acumulados, cliente_detalle_id) VALUES (1, b'1', 15000, 21);
INSERT INTO tbl_alumnos_cursos (alumno_id, curso_id) VALUES (20, 3);
INSERT INTO tbl_alumnos_cursos (alumno_id, curso_id) VALUES (20, 20);
INSERT INTO facturas (id, descripcion, total, id_cliente) VALUES (1, 'Compra de Laptop', 19999, 19);
INSERT INTO facturas (id, descripcion, total, id_cliente) VALUES (2, 'Boleto de avión a Huatulco', 2500, 19);
INSERT INTO facturas (id, descripcion, total, id_cliente) VALUES (3, 'Equipo de gimnasio', 8500, 7);
INSERT INTO facturas (id, descripcion, total, id_cliente) VALUES (4, 'Vestido de diseñador', 4800, 7);
