INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (1, 'Jesús', 'Zúñiga Trejo', 'Débito', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (2, 'Ana', 'Alejandre Arroyo', 'Crédito', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (3, 'Ada', 'Lovelace', 'Bitcoins', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (4, 'Ana', 'De Armas', 'Paypal', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (5, 'Alicia', 'Vikander', 'Débito', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (6, 'Amber', 'Heard', 'Crédito', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (7, 'Nathalie', 'Emmanuel', 'Dominican Peso', NULL, '2022-03-04 10:46:31');
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (8, 'Julia', 'Styles', 'Afghani', NULL, '2022-03-04 10:44:01');
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (9, 'Natalie', 'Dormer', 'European Unit of Account 9(E.U.A.-9)', NULL, '2022-03-04 10:50:25');
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (10, 'Rosa María', 'Villalobos', 'Djibouti Franc', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (11, 'Carice', 'Van Houten', 'Pound Sterling', NULL, '2022-03-04 10:47:32');
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (12, 'Monica', 'Galindo', 'Lithuanian Litas', NULL, '2022-03-04 10:43:06');
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (13, 'Estela', 'Rentería', 'US Dollar', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (14, 'Liliana', 'Ramírez', 'Rand', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (15, 'Martha', 'Aranda', 'Saudi Riyal', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (16, 'Edith', 'de la Torre', 'Sudanese Pound', NULL, NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (17, 'Leonor', 'Watling', 'Débito', '2022-03-04 10:23:25', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (18, 'Paz', 'Vega', 'Crédito', '2022-03-04 10:24:18', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (19, 'Maribel', 'Verdú', 'Efectivo', '2022-03-04 10:25:53', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (20, 'Elena', 'Anaya', 'Bitcoins', '2022-03-04 10:26:51', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (21, 'Natasha', 'Yarovenko', 'Paypal', '2022-03-04 10:27:46', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (22, 'Angie', 'Cepeda', 'Pesos Colombianos', '2022-03-04 10:28:47', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (23, 'Eréndira', 'Ibarra', 'Doláres Australianos', '2022-03-04 10:36:24', '2022-03-04 11:15:31');
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (24, 'Adriana', 'Paz', 'Pesos Mexicanos', '2022-03-04 11:09:56', NULL);
INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (25, 'Sasha', 'González', 'Pesos Mexicanos', '2022-03-04 11:13:23', NULL);
